In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [8]:
file = "/Users/radc/Desktop/PARTES_DE_ACCIDENTE_2020_25.xlsx"

xls = pd.ExcelFile(file)

print(xls.sheet_names)

['2020', '2021', '2022', '2023', '2024', '2025']

In [9]:
dfs = pd.read_excel(file, sheet_name=None)

In [ ]:
dfs.keys() # Verifico que tengo los nombres de todas las hojas

dict_keys(['2020', '2021', '2022', '2023', '2024', '2025'])

In [ ]:
df = pd.concat(
    [d.assign(sheet=name) for name, d in dfs.items()],
    ignore_index=True
) # Las concateno en un solo DF

In [12]:
df.head()

,NIF,Nombre,Apellido1,Apellido2,FechaParteAccidente,FechaAltaParte,Codigo,DescripcionParte,Actividad,Lugar,...,ActividadOrganizada,Festivo,NResponsables,TamañoGrupo,CentroHospitalizacion,DescripcionGrado,Pais,Provincia,TipoAccidente,sheet
0,10550152Y,JUAN,RODRIGUEZ,INCIARTE,2020-01-03 00:00:00,2020-01-04 12:06:00,743808511,Caída en pista de esquí en Baqueira,Esquí Alpino,Pista en Beret,...,False,False,1,3,NaN,Leve,España,LLEIDA,Deslizamiento por pendiente,2020
1,44625560V,IGNACIO,ARIÑO,GARRIDO,2020-01-03 10:00:00,2020-01-08 11:18:00,743809331,Resbalón como consecuencia se produce un impac...,Esquí Alpino,Formigal,...,False,False,1,1,NaN,Leve,España,HUESCA,Tropiezos (caída al mismo nivel),2020
2,70062257W,CARLOS,SELMAN,NEIRA,2020-01-03 11:00:00,2020-01-04 18:52:00,743808601,"Bajando por Peñalara, sufrí caída con golpe en...",Carreras por montaña,Puerto de Cotos,...,False,False,1,1,NaN,Leve,España,MADRID,Tropiezos (caída al mismo nivel),2020
3,11853175X,JUAN,CABRERO,PICO,2020-01-03 12:00:00,2020-01-07 12:13:00,743808501,Caída de esquí de montaña por la que pasadas u...,Esquí de montaña/Splitboard,Els Pedrons,...,False,False,1,1,NaN,Leve,Andorra,-,Deslizamiento por pendiente,2020
4,07516676T,FRANCISCO JAVIER,DE MARCO,MARTIN,2020-01-04 10:30:00,2020-01-07 08:48:00,743808521,Caminando por un sendero ascendente me resbalé...,Senderismo,Manzanares el Real,...,False,False,1,0,NaN,Leve,España,MADRID,Deslizamiento por pendiente,2020

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3982 entries, 0 to 3981
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NIF                    3982 non-null   str
 1   Nombre                 3982 non-null   str
 2   Apellido1              3982 non-null   str
 3   Apellido2              3981 non-null   str
 4   FechaParteAccidente    3982 non-null   datetime64[us]
 5   FechaAltaParte         3982 non-null   datetime64[us]
 6   Codigo                 3982 non-null   int64
 7   DescripcionParte       3982 non-null   str
 8   Actividad              3982 non-null   str
 9   Lugar                  3860 non-null   str
 10  FechaRecepcion         3982 non-null   datetime64[us]
 11  CentroUrgencias        1604 non-null   object
 12  Helicoptero            2 non-null      object
 13  MacizoMontañoso        3792 non-null   object
 14  NombreParaje           3817 non-null   object
 15  Entrenamiento          3982 non-null   bool
 16  ActividadPersonal      3982 non-null   bool
 17  ActividadOrganizada    3982 non-null   bool
 18  Festivo                3982 non-null   bool
 19  NResponsables          3982 non-null   int64
 20  TamañoGrupo            3982 non-null   int64
 21  CentroHospitalizacion  281 non-null    object
 22  DescripcionGrado       3830 non-null   str
 23  Pais                   3982 non-null   str
 24  Provincia              3982 non-null   str
 25  TipoAccidente          3982 non-null   str
 26  sheet                  3982 non-null   str
dtypes: bool(4), datetime64[us](3), int64(3), object(5), str(12)
memory usage: 731.2+ KB

In [ ]:
cols_keep = [
    "NIF",
    "FechaParteAccidente",
    "Actividad",
    "Lugar",
    "Provincia",
    "TipoAccidente",
    "DescripcionGrado",
    "TamañoGrupo",
    "NResponsables",
    "Entrenamiento",
    "ActividadPersonal",
    "ActividadOrganizada",
    "Festivo",
    "sheet"
]

df = df[cols_keep] # Las columnas que creo que nos pueden aportar información relevante para el análisis

In [15]:
df.head()

,NIF,FechaParteAccidente,Actividad,Lugar,Provincia,TipoAccidente,DescripcionGrado,TamañoGrupo,NResponsables,Entrenamiento,ActividadPersonal,ActividadOrganizada,Festivo,sheet
0,10550152Y,2020-01-03 00:00:00,Esquí Alpino,Pista en Beret,LLEIDA,Deslizamiento por pendiente,Leve,3,1,False,False,False,False,2020
1,44625560V,2020-01-03 10:00:00,Esquí Alpino,Formigal,HUESCA,Tropiezos (caída al mismo nivel),Leve,1,1,False,True,False,False,2020
2,70062257W,2020-01-03 11:00:00,Carreras por montaña,Puerto de Cotos,MADRID,Tropiezos (caída al mismo nivel),Leve,1,1,False,True,False,False,2020
3,11853175X,2020-01-03 12:00:00,Esquí de montaña/Splitboard,Els Pedrons,-,Deslizamiento por pendiente,Leve,1,1,False,True,False,False,2020
4,07516676T,2020-01-04 10:30:00,Senderismo,Manzanares el Real,MADRID,Deslizamiento por pendiente,Leve,0,1,False,True,False,False,2020

In [ ]:
df.info() # Nos quedamos con 14 de 26 columnas

<class 'pandas.DataFrame'>
Index: 3957 entries, 0 to 3981
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NIF                  3957 non-null   str
 1   FechaParteAccidente  3957 non-null   datetime64[us]
 2   Actividad            3957 non-null   str
 3   Lugar                3836 non-null   str
 4   Provincia            3957 non-null   str
 5   TipoAccidente        3957 non-null   str
 6   DescripcionGrado     3805 non-null   str
 7   TamañoGrupo          3957 non-null   int64
 8   NResponsables        3957 non-null   int64
 9   Entrenamiento        3957 non-null   bool
 10  ActividadPersonal    3957 non-null   bool
 11  ActividadOrganizada  3957 non-null   bool
 12  Festivo              3957 non-null   bool
 13  sheet                3957 non-null   str
dtypes: bool(4), datetime64[us](1), int64(2), str(7)
memory usage: 355.5 KB

In [17]:
df.duplicated().sum()

np.int64(8)

In [ ]:
dups = df[df.duplicated(
    subset=[
        "NIF",
        "FechaParteAccidente",
        "Lugar",
        "TipoAccidente"
    ],
    keep=False
)]

dups # Muestra los registros duplicados - los originales y las copias

,NIF,FechaParteAccidente,Actividad,Lugar,Provincia,TipoAccidente,DescripcionGrado,TamañoGrupo,NResponsables,Entrenamiento,ActividadPersonal,ActividadOrganizada,Festivo,sheet
87,05345381C,2020-02-18 14:00:00,Esquí Alpino,Cervinia,-,Tropiezos (caída al mismo nivel),Leve,2,1,False,True,False,False,2020
88,05345381C,2020-02-18 14:00:00,Esquí Alpino,Cervinia,-,Tropiezos (caída al mismo nivel),Leve,2,1,False,True,False,False,2020
317,04191894Y,2020-08-15 12:00:00,Alpinismo,PIC DE SERRE MOURÈNE CIRQUE DE TROUMOUSE.,-,Caída en vertical,Mortal,5,1,False,True,False,False,2020
318,04191894Y,2020-08-15 12:00:00,Alpinismo,PIC DE SERRE MOURÈNE CIRQUE DE TROUMOUSE.,-,Caída en vertical,Mortal,5,1,False,True,False,False,2020
380,51888566Z,2020-09-22 12:00:00,Senderismo,La Barranca,MADRID,Tropiezos (caída al mismo nivel),Leve,1,1,False,True,False,False,2020
381,51888566Z,2020-09-22 12:00:00,Senderismo,La Barranca,MADRID,Tropiezos (caída al mismo nivel),Leve,1,1,False,True,False,False,2020
1018,06988343T,2021-07-06 15:00:00,Montañismo/Progresión por terreno abrupto,"Cerca del refugio du Clot (Marcadau, Francia)",-,Tropiezos (caída al mismo nivel),Grave,9,1,False,True,False,False,2021
1019,06988343T,2021-07-06 15:00:00,Montañismo/Progresión por terreno abrupto,"Cerca del refugio du Clot (Marcadau, Francia)",-,Tropiezos (caída al mismo nivel),Grave,9,1,False,True,False,False,2021
1621,50688629X,2022-04-24 10:00:00,Senderismo,Bustarviejo,MADRID,Tropiezos (caída al mismo nivel),Grave,0,0,False,True,False,True,2022
1622,50688629X,2022-04-24 10:00:00,Senderismo,Bustarviejo,MADRID,Tropiezos (caída al mismo nivel),Leve,0,0,False,True,False,False,2022
2214,50676554X,2023-02-20 12:00:00,Esquí Alpino,Cortina Ampezzo,-,Tropiezos (caída al mismo nivel),Leve,16,2,False,False,True,False,2023
2215,50676554X,2023-02-20 12:00:00,Esquí Alpino,Cortina Ampezzo,-,Tropiezos (caída al mismo nivel),Leve,16,2,False,False,True,False,2023
2218,15941884D,2023-02-22 16:00:00,Esquí Alpino,Final del remonte Sodlisia,-,Tropiezos (caída al mismo nivel),Grave,0,0,False,True,False,False,2023
2219,15941884D,2023-02-22 16:00:00,Esquí Alpino,Final del remonte Sodlisia,-,Tropiezos (caída al mismo nivel),Grave,2,0,False,True,False,False,2023
2328,02665694V,2023-04-11 00:00:00,Senderismo,Nepal,EXTRANJERO,Problemas físicos,Leve,5,1,False,False,True,False,2023
2329,02665694V,2023-04-11 00:00:00,Senderismo,Nepal,EXTRANJERO,Problemas físicos,Leve,5,1,False,True,False,False,2023
2455,50636271T,2023-06-14 20:30:00,Rocódromo,Sputnik Las Rozas,MADRID,Colisión con personas,Leve,12,1,True,False,False,False,2023
2456,50636271T,2023-06-14 20:30:00,Rocódromo,Sputnik Las Rozas,MADRID,Colisión con personas,Leve,8,1,True,False,False,False,2023
2826,02302403B,2024-01-18 20:15:00,Rocódromo,Roc 30,MADRID,Caída en vertical,Leve,1,1,True,False,False,False,2024
2827,02302403B,2024-01-18 20:15:00,Rocódromo,Roc 30,MADRID,Caída en vertical,Leve,1,1,True,False,False,False,2024
3133,02442123Y,2024-06-25 16:00:00,Senderismo,Alcalá de Henares,MADRID,Problemas físicos,NaN,20,1,False,False,True,False,2024
3134,02442123Y,2024-06-25 16:00:00,Senderismo,Alcalá de Henares,MADRID,Problemas físicos,Leve,20,1,False,False,True,False,2024
3265,50451124A,2024-09-21 09:00:00,Carreras por montaña,Villaviciosa de Odón,MADRID,Tropiezos (caída al mismo nivel),Leve,0,0,True,False,False,False,2024
3266,50451124A,2024-09-21 09:00:00,Carreras por montaña,Villaviciosa de Odón,MADRID,Tropiezos (caída al mismo nivel),Leve,0,1,True,False,False,False,2024
3276,02282680E,2024-09-27 21:00:00,Carreras por montaña,Torrelodones,MADRID,Problemas físicos,Leve,1,0,True,False,False,False,2024
3277,02282680E,2024-09-27 21:00:00,Carreras por montaña,Torrelodones,MADRID,Problemas físicos,Leve,1,1,True,False,False,False,2024
3307,06026687C,2024-10-12 10:30:00,Escalada alta montaña,Finestrat,ALICANTE,Caída en vertical,Grave,2,2,False,True,False,False,2024
3308,06026687C,2024-10-12 10:30:00,Escalada alta montaña,Finestrat,ALICANTE,Caída en vertical,Grave,2,2,False,True,False,False,2024
3408,60249595Z,2024-12-15 00:00:00,Escalada alta montaña,Zarzalejo,MADRID,Caída en vertical,NaN,4,2,False,True,False,False,2024
3409,60249595Z,2024-12-15 00:00:00,Escalada alta montaña,Zarzalejo,MADRID,Caída en vertical,Leve,4,2,False,True,False,False,2024
3490,11843025A,2025-02-08 00:00:00,Escalada en hielo,Cascada de hielo,MADRID,Caída de piedras,Grave,0,0,False,True,False,False,2025
3491,11843025A,2025-02-08 00:00:00,Escalada en hielo,Cascada de hielo,-,Caída de piedras,Grave,0,0,False,True,False,False,2025
3534,02652024D,2025-03-02 16:00:00,Rocódromo,NaN,MADRID,Caída en vertical,Leve,0,0,True,False,False,False,2025
3535,02652024D,2025-03-02 16:00:00,Rocódromo,NaN,MADRID,Caída en vertical,Leve,0,0,True,False,False,False,2025
3769,06574261X,2025-08-01 10:00:00,Senderismo,El Berrocal,ÁVILA,Deslizamiento por pendiente,NaN,0,0,True,True,False,False,2025
3770,06574261X,2025-08-01 10:00:00,Senderismo,El Berrocal,ÁVILA,Deslizamiento por pendiente,Leve,0,0,True,True,False,False,2025

In [ ]:
dups[["NIF", "FechaParteAccidente", "sheet"]].sort_values(
    ["NIF", "FechaParteAccidente"]
) # Muestra los registros duplicados por hoja - doble comprobación de que son iguales

            NIF FechaParteAccidente sheet
3276  02282680E 2024-09-27 21:00:00  2024
3277  02282680E 2024-09-27 21:00:00  2024
2826  02302403B 2024-01-18 20:15:00  2024
2827  02302403B 2024-01-18 20:15:00  2024
3133  02442123Y 2024-06-25 16:00:00  2024
3134  02442123Y 2024-06-25 16:00:00  2024
3534  02652024D 2025-03-02 16:00:00  2025
3535  02652024D 2025-03-02 16:00:00  2025
2328  02665694V 2023-04-11 00:00:00  2023
2329  02665694V 2023-04-11 00:00:00  2023
317   04191894Y 2020-08-15 12:00:00  2020
318   04191894Y 2020-08-15 12:00:00  2020
87    05345381C 2020-02-18 14:00:00  2020
88    05345381C 2020-02-18 14:00:00  2020
3307  06026687C 2024-10-12 10:30:00  2024
3308  06026687C 2024-10-12 10:30:00  2024
3769  06574261X 2025-08-01 10:00:00  2025
3770  06574261X 2025-08-01 10:00:00  2025
1018  06988343T 2021-07-06 15:00:00  2021
1019  06988343T 2021-07-06 15:00:00  2021
3490  11843025A 2025-02-08 00:00:00  2025
3491  11843025A 2025-02-08 00:00:00  2025
2218  15941884D 2023-02-22 16:00:00  2023
2219  15941884D 2023-02-22 16:00:00  2023
3265  50451124A 2024-09-21 09:00:00  2024
3266  50451124A 2024-09-21 09:00:00  2024
2455  50636271T 2023-06-14 20:30:00  2023
2456  50636271T 2023-06-14 20:30:00  2023
2214  50676554X 2023-02-20 12:00:00  2023
2215  50676554X 2023-02-20 12:00:00  2023
1621  50688629X 2022-04-24 10:00:00  2022
1622  50688629X 2022-04-24 10:00:00  2022
380   51888566Z 2020-09-22 12:00:00  2020
381   51888566Z 2020-09-22 12:00:00  2020
3408  60249595Z 2024-12-15 00:00:00  2024
3409  60249595Z 2024-12-15 00:00:00  2024

In [ ]:
df = df.drop_duplicates(
    subset=[
        "NIF",
        "FechaParteAccidente",
        "sheet"
    ]
) # Elimino los registros duplicados, manteniendo solo uno de ellos (el original)

In [ ]:
df.duplicated(
    subset=[
        "NIF",
        "FechaParteAccidente",
        "sheet"
    ]
).sum() # Verificación de que ya no hay registros duplicados en el DataFrame final

np.int64(0)

In [ ]:
df["NIF"] = df["NIF"].astype(str).str.strip().str.upper() # Normalizo el formato de los NIF para evitar problemas de merge

In [ ]:
df["NIF"].isna().sum(), (df["NIF"]=="").sum() # Todos los NIF están completos, no hay valores nulos ni vacíos!

(np.int64(0), np.int64(0))

In [26]:
df["FechaParteAccidente"].isna().sum()

np.int64(0)